# Server
server.port=8080
server.shutdown=graceful
spring.application.name = ShopingPlusAssignment
# DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.properties.hibernate.format_sql=true
spring.jpa.properties.use_sql_comments=true
spring.jpa.open-in-view=false
#JWT
jwt.secret.key=YXNkZmFzZGZzYXdpMjA5MzQ4MjkyMXFrYXNkYXMxMjQyM2xrajQzams0MzJqazMybGs=
jwt.accessToken.time=3600000
jwt.refreshToken.time=1209600000
#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3000
spring.data.redis.password=1234




